server:
  port: 8080
spring:
  application:
    name: weather-rest-api
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
openWeather:
  baseURI: https://api.openweathermap.org/data/2.5/weather
  apiKey: test
tokenLimit: 5
---
spring:
  config:
    activate:
      on-profile: test
openWeather:
  apiKey: test
tokenLimit: 20